### DISCUSSION TITLE
Get error "Cannot bind argument to parameter 'Path' because it is null" using AWSPowerShellModuleScript@1 every now and then in Azure Devops pipeline

### DISCUSSION THREAD

**Discussion by khemebuen** [aws/aws-tools-for-powershell#352] [Q&A] [answered]
We are using Azure Devops and are running terraform which stores state files in S3.  When we use AWSPowerShellModuleScript@1 every now and then we get the error  "Cannot bind argument to parameter 'Path' because it is null".  At times when we replay the stage it works but most of the time we replay and it still fails with same error.

Or yaml snippet is llike this
```
  - task: AWSPowerShellModuleScript@1
    displayName: "Terraform Plan"
    name: "terraformPlanTask"
    inputs:
      awsCredentials: '${{ parameters.awsCredentials }}'
      regionName: '${{ parameters.awsRegion }}'
      scriptType: 'inline'
      inlineScript: |
        terraform init -upgrade -backend-config="${{ parameters.backendConfigFile }}"

        terraform validate
```

We are running on Windows vms's hosted on Azure.  

Here is a snppet of the error
![image](https://github.com/aws/aws-tools-for-powershell/assets/23692976/f8ff9217-fdf6-4620-be5e-0da62fb10937)
